
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - chat
  - vendor

sass:
  style: compressed

author: Adriane Justine Tan
email: eidoriantan@gmail.com

tagline: Chat with another anonymous users
color: "#24292e"

websocket:
  hostname: 52.149.182.90
  port: 80

plugins:
  - jekyll-github-metadata
  - jekyll-octicons
  - jekyll-seo-tag
  - jekyll-sitemap
