
exclude:
  - chat/
  - vendor/
  - CNAME
  - composer.json
  - composer.lock
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  style: compressed

author: Adriane Justine Tan
email: eidoriantan@gmail.com

tagline: Chat with another anonymous users
color: "#f8f9fa"

websocket:
  hostname: chatapp-websocket.eastus.cloudapp.azure.com
  port: 8000

plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
